export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const SET_COUNTRY_CODE = 'SET_COUNTRY_CODE'

export const SENDBIRD_CONNECT = 'SENDBIRD_CONNECT'
export const SENDBIRD_CONNECT_ERROR = 'SENDBIRD_CONNECT_ERROR'
export const SENDBIRD_CONNECTED = 'SENDBIRD_CONNECTED'
export const SENDBIRD_SET_USER = 'SENDBIRD_SET_USER'

export const SENDBIRD_LIST_CHANNELS = 'SENDBIRD_LIST_CHANNELS'
export const SENDBIRD_LIST_CHANNELS_ERROR = 'SENDBIRD_LIST_CHANNELS_ERROR'
